const fs   = require('fs');
const solc = require('solc');

const VIA_IR   = true;
const OPTIMIZE = 200;

/* ── 读源码 ── */
const tokenPath = './contracts-simple/ModaMintToken.sol';
const tokenSrc  = fs.readFileSync(tokenPath, 'utf8');

/* ── 编译 ModaMintToken ── */
console.log('⚙️  编译 ModaMintToken (viaIR=' + VIA_IR + ', runs=' + OPTIMIZE + ')...');
const input = JSON.stringify({
  language: 'Solidity',
  sources: { 'ModaMintToken.sol': { content: tokenSrc } },
  settings: {
    viaIR: VIA_IR,
    optimizer: { enabled: true, runs: OPTIMIZE },
    evmVersion: 'london',
    outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object', 'evm.bytecode.sourceMap',
      'evm.deployedBytecode.object', 'evm.deployedBytecode.sourceMap'], '': ['id'] } }
  }
});
const output = JSON.parse(solc.compile(input));
if (output.errors) {
  output.errors.filter(e => e.severity === 'error').forEach(e => { console.error(e.formattedMessage); process.exit(1); });
  output.errors.forEach(e => console.warn('⚠️ ', e.formattedMessage || e.message));
}

/* ── 提取两个合约 ── */
const tokenAbi     = output.contracts['ModaMintToken.sol'].ModaMintToken.abi;
const tokenByte    = '0x' + output.contracts['ModaMintToken.sol'].ModaMintToken.evm.bytecode.object;
const trackerAbi   = output.contracts['ModaMintToken.sol'].ModaDividendTracker.abi;
const trackerByte  = '0x' + output.contracts['ModaMintToken.sol'].ModaDividendTracker.evm.bytecode.object;

// 写入 contract_data.js
fs.writeFileSync('contract_data.js',
  '// Auto-generated by compile.js — DO NOT EDIT\nvar CONTRACT_DATA = {\n  ABI: ' +
  JSON.stringify(tokenAbi, null, 2) + ',\n  BYTECODE: \"' + tokenByte + '\"\n};\n');
console.log('✅ contract_data.js 已更新 (ModaMintToken)');

// 写入 tracker_data.js
fs.writeFileSync('tracker_data.js',
  '// Auto-generated by compile.js — DO NOT EDIT\nvar TRACKER_DATA = {\n  ABI: ' +
  JSON.stringify(trackerAbi, null, 2) + ',\n  BYTECODE: \"' + trackerByte + '\"\n};\n');
console.log('✅ tracker_data.js 已更新 (ModaDividendTracker)');

// 写入 standard-input.json（BscScan 验证用）
fs.writeFileSync('standard-input.json', JSON.stringify({
  language: 'Solidity',
  sources: { 'ModaMintToken.sol': { content: tokenSrc } },
  settings: {
    viaIR: VIA_IR,
    optimizer: { enabled: true, runs: OPTIMIZE },
    evmVersion: 'london',
    outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object', 'evm.bytecode.sourceMap',
      'evm.deployedBytecode.object', 'evm.deployedBytecode.sourceMap'], '': ['id'] } }
  }
}, null, 2));
console.log('✅ standard-input.json 已更新（BscScan 验证用）');

console.log('\n🎉 全部完成！');
