const fs   = require('fs');
const path = require('path');
const solc = require('solc');

const VIA_IR      = true;
const OPTIMIZE    = 200;
const TAX_VIA_IR   = false;
const TAX_OPTIMIZE = 10000;
const ROOT         = __dirname;

/* ── 读源码 ── */
const tokenPath = path.join(ROOT, 'contracts-simple/ModaMintToken.sol');
const tokenSrc  = fs.readFileSync(tokenPath, 'utf8');
const taxPath   = path.join(ROOT, 'contracts-simple/TaxDistributor.sol');
const taxSrc    = fs.readFileSync(taxPath, 'utf8');

/* ── 编译 ModaMintToken ── */
console.log('⚙️  编译 ModaMintToken (viaIR=' + VIA_IR + ', runs=' + OPTIMIZE + ')...');
const input = JSON.stringify({
  language: 'Solidity',
  sources: { 'ModaMintToken.sol': { content: tokenSrc } },
  settings: {
    viaIR: VIA_IR,
    optimizer: { enabled: true, runs: OPTIMIZE },
    evmVersion: 'london',
    outputSelection: {
      '*': {
        '*': ['abi', 'evm.bytecode.object', 'evm.bytecode.sourceMap',
              'evm.deployedBytecode.object', 'evm.deployedBytecode.sourceMap'],
        '': ['id']
      }
    }
  }
});
const output = JSON.parse(solc.compile(input));
if (output.errors) {
  output.errors.filter(e => e.severity === 'error').forEach(e => { console.error(e.formattedMessage); process.exit(1); });
  output.errors.forEach(e => console.warn('⚠️ ', e.formattedMessage || e.message));
}

/* ── 提取两个合约 ── */
const tokenAbi    = output.contracts['ModaMintToken.sol'].ModaMintToken.abi;
const tokenByte   = '0x' + output.contracts['ModaMintToken.sol'].ModaMintToken.evm.bytecode.object;
const trackerAbi  = output.contracts['ModaMintToken.sol'].ModaDividendTracker.abi;
const trackerByte = '0x' + output.contracts['ModaMintToken.sol'].ModaDividendTracker.evm.bytecode.object;

fs.writeFileSync(
  path.join(ROOT, 'contract_data.js'),
  '// Auto-generated by compile.js — DO NOT EDIT\nvar CONTRACT_DATA = {\n  ABI: ' +
  JSON.stringify(tokenAbi, null, 2) + ',\n  BYTECODE: "' + tokenByte + '"\n};\n'
);
console.log('✅ contract_data.js 已更新 (ModaMintToken)');

fs.writeFileSync(
  path.join(ROOT, 'tracker_data.js'),
  '// Auto-generated by compile.js — DO NOT EDIT\nvar TRACKER_DATA = {\n  ABI: ' +
  JSON.stringify(trackerAbi, null, 2) + ',\n  BYTECODE: "' + trackerByte + '"\n};\n'
);
console.log('✅ tracker_data.js 已更新 (ModaDividendTracker)');

// 写入 standard-input.json（BscScan 验证用 — ModaMintToken）
fs.writeFileSync(
  path.join(ROOT, 'standard-input.json'),
  JSON.stringify({
    language: 'Solidity',
    sources: { 'ModaMintToken.sol': { content: tokenSrc } },
    settings: {
      viaIR: VIA_IR,
      optimizer: { enabled: true, runs: OPTIMIZE },
      evmVersion: 'london',
      outputSelection: {
        '*': {
          '*': ['abi', 'evm.bytecode.object', 'evm.bytecode.sourceMap',
                'evm.deployedBytecode.object', 'evm.deployedBytecode.sourceMap'],
          '': ['id']
        }
      }
    }
  }, null, 2)
);
console.log('✅ standard-input.json 已更新（BscScan 验证用 — ModaMintToken）');

/* ── 编译 TaxDistributor ── */
console.log('⚙️  编译 TaxDistributor (viaIR=' + TAX_VIA_IR + ', runs=' + TAX_OPTIMIZE + ')...');
const taxInput = JSON.stringify({
  language: 'Solidity',
  sources: { 'TaxDistributor.sol': { content: taxSrc } },
  settings: {
    viaIR: TAX_VIA_IR,
    optimizer: { enabled: true, runs: TAX_OPTIMIZE },
    evmVersion: 'london',
    outputSelection: {
      '*': {
        '*': ['abi', 'evm.bytecode.object', 'evm.bytecode.sourceMap',
              'evm.deployedBytecode.object', 'evm.deployedBytecode.sourceMap'],
        '': ['id']
      }
    }
  }
});
const taxOutput = JSON.parse(solc.compile(taxInput));
if (taxOutput.errors) {
  taxOutput.errors.filter(e => e.severity === 'error').forEach(e => { console.error(e.formattedMessage); process.exit(1); });
  taxOutput.errors.forEach(e => console.warn('⚠️ ', e.formattedMessage || e.message));
}
const taxAbi  = taxOutput.contracts['TaxDistributor.sol'].TaxDistributor.abi;
const taxByte = '0x' + taxOutput.contracts['TaxDistributor.sol'].TaxDistributor.evm.bytecode.object;

fs.writeFileSync(
  path.join(ROOT, 'tax_distributor_data.js'),
  '// Auto-generated by compile.js — DO NOT EDIT\nvar TAX_DISTRIBUTOR_DATA = {\n  ABI: ' +
  JSON.stringify(taxAbi, null, 2) + ',\n  BYTECODE: "' + taxByte + '"\n};\n'
);
console.log('✅ tax_distributor_data.js 已更新 (TaxDistributor)');

// 写入 standard-input-tax.json（BscScan 验证用 — TaxDistributor）
fs.writeFileSync(
  path.join(ROOT, 'standard-input-tax.json'),
  JSON.stringify({
    language: 'Solidity',
    sources: { 'TaxDistributor.sol': { content: taxSrc } },
    settings: {
      viaIR: TAX_VIA_IR,
      optimizer: { enabled: true, runs: TAX_OPTIMIZE },
      evmVersion: 'london',
      outputSelection: {
        '*': {
          '*': ['abi', 'evm.bytecode.object', 'evm.bytecode.sourceMap',
                'evm.deployedBytecode.object', 'evm.deployedBytecode.sourceMap'],
          '': ['id']
        }
      }
    }
  }, null, 2)
);
console.log('✅ standard-input-tax.json 已更新（BscScan 验证用 — TaxDistributor）');

console.log('\n🎉 全部完成！');
